### ISSUE TITLE
组织邀请成功完 从通道无法获取对应节点，且无法上链，成员移除完又正常

### ISSUE THREAD

**Issue by suzhiliang** [hyperledger/fabric#3100]
java.util.concurrent.ExecutionException: org.hyperledger.fabric.sdk.exception.TransactionEventException: Received invalid transaction event. Transaction ID 512e862f60061ba8017f7af3de780ade2ef401b7fe7a90dec9d91b9e0cfd279c status 10
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
        at com.linewell.blockchain.base.FabricUtils.commit(FabricUtils.java:408)
        at com.linewell.blockchain.base.FabricUtils.blockChainWrite(FabricUtils.java:470)
        at com.linewell.blockchain.cloud.core.service.impl.BlockChainWriteInServiceImpl.write(BlockChainWriteInServiceImpl.java:158)
        at com.linewell.blockchain.cloud.core.service.impl.sumkbox.BlockChainWriteInServiceImpl.write(BlockChainWriteInServiceImpl.java)
        at com.linewell.blockchain.cloud.core.api.adapter.network.impl.LWBcNetworkImpl.write(LWBcNetworkImpl.java:56)
        at com.linewell.blockchain.cloud.core.service.impl.LicenseServiceImpl.addChain(LicenseServiceImpl.java:648)
        at com.linewell.blockchain.cloud.core.service.impl.sumkbox.LicenseServiceImpl.addChain(LicenseServiceImpl.java)
        at com.linewell.blockchain.cloud.core.api.impl.BlockchainSDKApiImpl.moni(BlockchainSDKApiImpl.java:224)
        at com.alibaba.dubbo.common.bytecode.Wrapper28.invokeMethod(Wrapper28.java)
        at com.alibaba.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:47)
        at com.alibaba.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:76)
        at com.alibaba.dubbo.config.invoker.DelegateProviderMetaDataInvoker.invoke(DelegateProviderMetaDataInvoker.java:52)
        at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:56)
        at com.alibaba.dubbo.plugin.ExeceptionHandler.invoke(ExeceptionHandler.java:22)
        at com.alibaba.dubbo.plugin.FilterWrapper.invoke(FilterWrapper.java:87)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
        at com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38)
        at com.alibaba.dubbo.plugin.FilterWrapper.invoke(FilterWrapper.java:89)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
        at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:38)
        at com.alibaba.dubbo.plugin.FilterWrapper.invoke(FilterWrapper.java:89)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
        at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75)
        at com.alibaba.dubbo.plugin.FilterWrapper.invoke(FilterWrapper.java:89)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
        at com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:131)
        at com.alibaba.dubbo.plugin.FilterWrapper.invoke(FilterWrapper.java:89)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
        at com.alibaba.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:42)
        at com.alibaba.dubbo.plugin.FilterWrapper.invoke(FilterWrapper.java:89)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
        at com.alibaba.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:78)
        at com.alibaba.dubbo.plugin.FilterWrapper.invoke(FilterWrapper.java:89)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
        at com.alibaba.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:72)
        at com.alibaba.dubbo.plugin.FilterWrapper.handleRequestWithNoPlugin(FilterWrapper.java:104)
        at com.alibaba.dubbo.plugin.FilterWrapper.invoke(FilterWrapper.java:85)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
        at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:103)
        at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:96)
        at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:172)
        at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
        at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:80)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.hyperledger.fabric.sdk.exception.TransactionEventException: Received invalid transaction event. Transaction ID 512e862f60061ba8017f7af3de780ade2ef401b7fe7a90dec9d91b9e0cfd279c status 10
        at org.hyperledger.fabric.sdk.Channel$TL.lambda$2(Channel.java:6620)
        ... 3 more

**Comment by guoger** [comment]
First of all, please submit issue in English so others could actually understand your question. Your issue title could be translated to **Neither can peer info be retrieved from channel nor can transaction be submitted successfully, despite that the org has been added. After removing the org, all back to normal**

Secondly, it's pretty hard to debug your problem without more context - reproduce steps, code samples, etc - especially when you are using some custom code that we don't have access to

could you come back with more info? thx

**Comment by denyeart** [comment]
Please re-open when you provide the additional context.

**Comment by suzhiliang** [comment]
The issue has been resolved.The organization certificates linked to the channel were passed incorrectly, and were passed to the certificate of the owner of the federation chain, resulting in  
Newly invited organizations cannot be connected
