### ISSUE TITLE
Peer issue when starting

### ISSUE THREAD

**Issue by danielpenagos** [hyperledger/fabric#3201]
Image version: hyperledger/fabric-peer:1.4.12

Hello, I am facing a problem with a peer, which is not starting due to the following error:

![image](https://user-images.githubusercontent.com/3498160/151578064-d27e3e79-dd49-4ceb-99af-10dd24749c6f.png)

We have several chaincodes installed, and the issue started appearing yesterday. 
![image](https://user-images.githubusercontent.com/3498160/151578597-63a366a2-74e3-45f9-92b9-c61db2d1b2e1.png)

After reviewing the sourcecode, it seems to me, something could be wrong with one installed chaincode, but the exception is not handled yet. 

![image](https://user-images.githubusercontent.com/3498160/151580017-cfea24de-a92f-4f66-b010-1230d435e47b.png)

**Comment by danielpenagos** [comment]
I was reviewing the chaincodes folder, and found an empty file there.
![image](https://user-images.githubusercontent.com/3498160/151582652-fcb1c689-5d87-43f7-9d2a-d529ef8923e4.png)
Deleting that file solved the issue. I hope it would be helpful for someone else.

**Comment by danielpenagos** [comment]
I just copy part of the stack trace, in order to be indexed properly in case someone else had the issue. 

`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1166aca]

goroutine 1 [running]:
github.com/hyperledger/fabric/core/common/ccprovider.(*CDSPackage).getCDSData(0xc00029f800, 0xc0004dc5f0, 0x200, 0x19d6ae0, 0xc0004dc5f0, 0x0, 0x0, 0xc000298440, 0x15b8700, 0xc000298450, ...)
	/opt/gopath/src/github.com/hyperledger/fabric/core/common/ccprovider/cdspackage.go:153 +0x23a
github.com/hyperledger/fabric/core/common/ccprovider.(*CDSPackage).InitFromBuffer(0xc00029f800, 0xc002bb4000, 0x0, 0x200, 0xc000408a20, 0x26, 0xc002bb4000)
	/opt/gopath/src/github.com/hyperledger/fabric/core/common/ccprovider/cdspackage.go:223 +0xd2
github.com/hyperledger/fabric/core/common/ccprovider.(*CDSPackage).InitFromPath(0xc00029f800, 0xc0005a1a67, 0x11, 0xc0005a1a79, 0xc, 0xc000408a20, 0x26, 0xc0036f8000, 0x5bf23, 0x5c123, ...)
	/opt/gopath/src/github.com/hyperledger/fabric/core/common/ccprovider/cdspackage.go:247 +0xe6
`
