### ISSUE TITLE
I nead help fixing an incompatability with a fabric mod

### ISSUE THREAD

**Issue by POH1** [hyperledger/fabric#3213]
java.lang.RuntimeException: Non-unique Mixin config name mixins.reach-entity-attributes.json used by the mods feudalw and reach-entity-attributes
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:85)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by denyeart** [comment]
I think you are looking for https://github.com/FabricMC
