### ISSUE TITLE
panic: nil pointer in key-level endorsement use case

### ISSUE THREAD

**Issue by davidkhala** [hyperledger/fabric#3331]
In some case, the combination of using new fabric-gateway and key-level endorsement together disclose a vulnerability. 

some mis-configured fabric-gateway usage can kill the processing peer

Please consider it as bug.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x145daac]

goroutine 37146 [running]:
github.com/hyperledger/fabric/common/policies/inquire.principalsOfTree(0xc005b9c7a8, {0x0, 0x0, 0x1})
        /go/src/github.com/hyperledger/fabric/common/policies/inquire/inquire.go:65 +0x10c
github.com/hyperledger/fabric/common/policies/inquire.(*inquireableSignaturePolicy).SatisfiedBy(0xc005b9c8d8)
        /go/src/github.com/hyperledger/fabric/common/policies/inquire/inquire.go:44 +0x248
github.com/hyperledger/fabric/discovery/endorsement.computeStateBasedPrincipalSets({0xc0058712b8, 0x1, 0x0}, 0xc005b9caa8)
        /go/src/github.com/hyperledger/fabric/discovery/endorsement/endorsement.go:232 +0x45c
github.com/hyperledger/fabric/discovery/endorsement.(*endorsementAnalyzer).computePrincipalSets(0xc000340200, {0xc004336200, 0xa, 0xc003639980}, 0xc004493080)
        /go/src/github.com/hyperledger/fabric/discovery/endorsement/endorsement.go:308 +0x677
github.com/hyperledger/fabric/discovery/endorsement.(*endorsementAnalyzer).PeersForEndorsement(0xc000340200, {0xc004336200, 0xa, 0x10}, 0xc004493080)
        /go/src/github.com/hyperledger/fabric/discovery/endorsement/endorsement.go:95 +0x1cf
github.com/hyperledger/fabric/internal/pkg/gateway.(*registry).endorsementPlan(0xc00032e6e0, {0xc003ac7440, 0xa}, 0x0, 0xc0003302a0)
        /go/src/github.com/hyperledger/fabric/internal/pkg/gateway/registry.go:55 +0x8f
github.com/hyperledger/fabric/internal/pkg/gateway.(*Server).planFromFirstEndorser(0xc000149b00, {0x19dba00, 0xc00505c0c0}, {0xc003ac7440, 0xa}, {0xc003ac7460, 0xcc3065}, 0x0, 0xc004579ef0, 0xc00033de80)
        /go/src/github.com/hyperledger/fabric/internal/pkg/gateway/api.go:351 +0x8ba
github.com/hyperledger/fabric/internal/pkg/gateway.(*Server).Endorse(0xc000149b00, {0x19dba00, 0xc00505c0c0}, 0xc00533bb00)
        /go/src/github.com/hyperledger/fabric/internal/pkg/gateway/api.go:172 +0x706
github.com/hyperledger/fabric-protos-go/gateway._Gateway_Endorse_Handler.func1({0x19dba00, 0xc00505c0c0}, {0x17982c0, 0xc00533bb00})
        /go/src/github.com/hyperledger/fabric/vendor/github.com/hyperledger/fabric-protos-go/gateway/gateway.pb.go:1110 +0x78
github.com/hyperledger/fabric/internal/peer/node.unaryGrpcLimiter.func1({0x19dba00, 0xc00505c0c0}, {0x17982c0, 0xc00533bb00}, 0x180363e, 0xc00548c768)
        /go/src/github.com/hyperledger/fabric/internal/peer/node/grpc_limiters.go:56 +0x313
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x19dba00, 0xc00505c0c0}, {0x17982c0, 0xc00533bb00})
        /go/src/github.com/hyperledger/fabric/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:25 +0x3a
github.com/hyperledger/fabric/common/grpclogging.UnaryServerInterceptor.func1({0x19dba00, 0xc0054ffe90}, {0x17982c0, 0xc00533bb00}, 0xc0046968c0, 0xc0046968e0)
        /go/src/github.com/hyperledger/fabric/common/grpclogging/server.go:92 +0x305
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x19dba00, 0xc0054ffe90}, {0x17982c0, 0xc00533bb00})
        /go/src/github.com/hyperledger/fabric/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:25 +0x3a
github.com/hyperledger/fabric/common/grpcmetrics.UnaryServerInterceptor.func1({0x19dba00, 0xc0054ffe90}, {0x17982c0, 0xc00533bb00}, 0x18, 0xc004696900)
        /go/src/github.com/hyperledger/fabric/common/grpcmetrics/interceptor.go:31 +0x17b
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x19dba00, 0xc0054ffe90}, {0x17982c0, 0xc00533bb00})
        /go/src/github.com/hyperledger/fabric/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:25 +0x3a
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1({0x19dba00, 0xc0054ffe90}, {0x17982c0, 0xc00533bb00}, 0xc005f4fbb8, 0x1663660)
        /go/src/github.com/hyperledger/fabric/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34 +0xbf
github.com/hyperledger/fabric-protos-go/gateway._Gateway_Endorse_Handler({0x1747dc0, 0xc000149b00}, {0x19dba00, 0xc0054ffe90}, 0xc00533baa0, 0xc00021d830)
        /go/src/github.com/hyperledger/fabric/vendor/github.com/hyperledger/fabric-protos-go/gateway/gateway.pb.go:1112 +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00054e540, {0x19f1a50, 0xc00450e600}, 0xc00453a600, 0xc000328660, 0x223d740, 0xc0045533c0)
        /go/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/server.go:1180 +0xc8f
google.golang.org/grpc.(*Server).handleStream(0xc00054e540, {0x19f1a50, 0xc00450e600}, 0xc00453a600, 0xc0045533c0)
        /go/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/server.go:1503 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /go/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/server.go:843 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /go/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/server.go:841 +0x294
```

**Comment by yacovm** [comment]
@davidkhala what is the endorsement policy? (the key one)

**Comment by yacovm** [comment]
[This](https://github.com/hyperledger/fabric/pull/3334) should fix it.

**Comment by davidkhala** [comment]
> policy

In this scenario, the endorsement policy I am using is like `AND(Org1.member, Org2.member)`

**Comment by davidkhala** [comment]
> [This](https://github.com/hyperledger/fabric/pull/3334) should fix it.

I think so.
