### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference in ledger snapshot comparision

### ISSUE THREAD

**Issue by SecTechTool** [hyperledger/fabric#3878]
#### System information

fabric version: release-2.5
OS & Version: Linux

#### Expected behaviour
Run ledger snapshot comparison as normal.

#### Actual behaviour
panic: runtime error: invalid memory address or nil pointer dereference in SnapshotReader

#### Backtrace

Root location:
https://github.com/hyperledger/fabric/blob/release-2.5/core/ledger/kvledger/txmgmt/privacyenabledstate/snapshot.go
```
	if !exist {
		logger.Infow("Data file does not exist. Nothing to be done.", "filepath", dataFilePath)
		return nil, nil
	}
```
In line 450, returns snapshotReader as nil.

```
func (r *SnapshotReader) Next() (string, *SnapshotRecord, error) {
	if !r.cursor.move() {
		return "", nil, nil
	}

	snapshotRecord := &SnapshotRecord{}
	if err := r.dataFile.DecodeProtoMessage(snapshotRecord); err != nil {
		return "", nil, errors.WithMessage(err, "error while retrieving record from snapshot file")
	}
	return r.cursor.currentNamespace(), snapshotRecord, nil
}

```
In lines 504-514, uses the SnapshotReader without a nil checking.

log info:
````
panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1524d26]
 

goroutine 1 [running]:

github.com/hyperledger/fabric/core/ledger/kvledger/txmgmt/privacyenabledstate.(*SnapshotReader).Next(0x0, 0x0, 0x0, 0xc0000e4280, 0x0, 0x0)
 github.com/hyperledger/fabric/core/ledger/kvledger/txmgmt/privacyenabledstate/snapshot.go:505 +0x26
github.com/hyperledger/fabric/internal/ledgerutil.Compare(0x7ffeefbff997, 0x43, 0x7ffeefbff9db, 0x4b, 0x16c4950, 0xd, 0x0, 0x0)
github.com/hyperledger/fabric/internal/ledgerutil/compare/compare.go:144 +0x5f1
main.main()
github.com/hyperledger/fabric/cmd/ledgerutil/main.go:72 +0x259

````

**Comment by denyeart** [comment]
@BlockFuzz How did you build the binary? Or where did you pick up the binary?

**Comment by denyeart** [comment]
I believe this is resolved with the new image and binary approach, please try v2.5.0-beta and re-open if still an issue.
