### ISSUE TITLE
Development Mode documentation incorrect, still references Solo ordering service implementation.

### ISSUE THREAD

**Issue by hm3736485** [hyperledger/fabric#3887]
[Issue 3514](https://github.com/hyperledger/fabric/issues/3514) states that solo support is being depreciated. The Fabric documentation states that [Solo support is depreciated as of 2.x](https://hyperledger-fabric.readthedocs.io/en/latest/orderer/ordering_service.html?highlight=solo#ordering-service-implementations)

However, the documentation for starting the network in [development mode](https://hyperledger-fabric.readthedocs.io/en/latest/peer-chaincode-devmode.html#running-chaincode-in-development-mode) still references the Solo ordering implementation, and even says that [no edits need to be made to the default configuration](https://hyperledger-fabric.readthedocs.io/en/latest/peer-chaincode-devmode.html#running-chaincode-in-development-mode):

`It uses all the default settings for the peer and orderer and overrides the configurations using environment variables from the command line as needed. No edits are required to the default peer core.yaml or orderer orderer.yaml files.`

Attempting to start the orderer when configuring development mode as per the documentation results in the following error:

```
❯ ORDERER_GENERAL_GENESISPROFILE=SampleDevModeSolo orderer

2023-01-02 21:02:45.507 GMT 0001 INFO [orderer.common.server] prettyPrintStruct -> Orderer config values:
	General.ListenAddress = "127.0.0.1"
	General.ListenPort = 7050
	General.TLS.Enabled = false
	General.TLS.PrivateKey = "/home/test/go/src/github.com/hm3736485/fabric/sampleconfig/tls/server.key"
	General.TLS.Certificate = "/home/test/go/src/github.com/hm3736485/fabric/sampleconfig/tls/server.crt"
	General.TLS.RootCAs = [/home/test/go/src/github.com/hm3736485/fabric/sampleconfig/tls/ca.crt]
	General.TLS.ClientAuthRequired = false
	General.TLS.ClientRootCAs = []
	General.TLS.TLSHandshakeTimeShift = 0s
	General.Cluster.ListenAddress = ""
	General.Cluster.ListenPort = 0
	General.Cluster.ServerCertificate = ""
	General.Cluster.ServerPrivateKey = ""
	General.Cluster.ClientCertificate = ""
	General.Cluster.ClientPrivateKey = ""
	General.Cluster.RootCAs = []
	General.Cluster.DialTimeout = 5s
	General.Cluster.RPCTimeout = 7s
	General.Cluster.ReplicationBufferSize = 20971520
	General.Cluster.ReplicationPullTimeout = 5s
	General.Cluster.ReplicationRetryTimeout = 5s
	General.Cluster.ReplicationBackgroundRefreshInterval = 5m0s
	General.Cluster.ReplicationMaxRetries = 12
	General.Cluster.SendBufferSize = 100
	General.Cluster.CertExpirationWarningThreshold = 168h0m0s
	General.Cluster.TLSHandshakeTimeShift = 0s
	General.Keepalive.ServerMinInterval = 1m0s
	General.Keepalive.ServerInterval = 2h0m0s
	General.Keepalive.ServerTimeout = 20s
	General.ConnectionTimeout = 0s
	General.GenesisMethod = ""
	General.GenesisFile = ""
	General.BootstrapMethod = "file"
	General.BootstrapFile = "/home/test/go/src/github.com/hm3736485/fabric/sampleconfig/genesisblock"
	General.Profile.Enabled = false
	General.Profile.Address = "0.0.0.0:6060"
	General.LocalMSPDir = "/home/test/go/src/github.com/hm3736485/fabric/sampleconfig/msp"
	General.LocalMSPID = "SampleOrg"
	General.BCCSP.Default = "SW"
	General.BCCSP.SW.Security = 256
	General.BCCSP.SW.Hash = "SHA2"
	General.BCCSP.SW.FileKeystore.KeyStorePath = ""
	General.Authentication.TimeWindow = 15m0s
	General.Authentication.NoExpirationChecks = false
	General.MaxRecvMsgSize = 104857600
	General.MaxSendMsgSize = 104857600
	FileLedger.Location = "/var/hyperledger/production/orderer"
	FileLedger.Prefix = ""
	Debug.BroadcastTraceDir = ""
	Debug.DeliverTraceDir = ""
	Consensus = map[SnapDir:/var/hyperledger/production/orderer/etcdraft/snapshot WALDir:/var/hyperledger/production/orderer/etcdraft/wal]
	Operations.ListenAddress = "127.0.0.1:8443"
	Operations.TLS.Enabled = false
	Operations.TLS.PrivateKey = ""
	Operations.TLS.Certificate = ""
	Operations.TLS.RootCAs = []
	Operations.TLS.ClientAuthRequired = false
	Operations.TLS.ClientRootCAs = []
	Operations.TLS.TLSHandshakeTimeShift = 0s
	Metrics.Provider = "disabled"
	Metrics.Statsd.Network = "udp"
	Metrics.Statsd.Address = "127.0.0.1:8125"
	Metrics.Statsd.WriteInterval = 30s
	Metrics.Statsd.Prefix = ""
	ChannelParticipation.Enabled = false
	ChannelParticipation.MaxRequestBodySize = 1048576
	Admin.ListenAddress = "127.0.0.1:9443"
	Admin.TLS.Enabled = false
	Admin.TLS.PrivateKey = ""
	Admin.TLS.Certificate = ""
	Admin.TLS.RootCAs = []
	Admin.TLS.ClientAuthRequired = true
	Admin.TLS.ClientRootCAs = []
	Admin.TLS.TLSHandshakeTimeShift = 0s
2023-01-02 21:02:45.542 GMT 0002 INFO [blkstorage] NewProvider -> Creating new file ledger directory at /var/hyperledger/production/orderer/chains
2023-01-02 21:02:45.549 GMT 0003 INFO [orderer.common.server] Main -> Bootstrapping the system channel
2023-01-02 21:02:45.556 GMT 0004 INFO [blkstorage] newBlockfileMgr -> Getting block information from block storage
2023-01-02 21:02:45.564 GMT 0005 INFO [orderer.common.server] initializeBootstrapChannel -> Initialized the system channel 'syschannel' from bootstrap block
2023-01-02 21:02:45.566 GMT 0006 INFO [orderer.common.server] extractSystemChannel -> Found system channel config block, number: 0
2023-01-02 21:02:45.566 GMT 0007 INFO [orderer.common.server] selectClusterBootBlock -> Cluster boot block is bootstrap (genesis) block; Blocks Header.Number system-channel=0, bootstrap=0
2023-01-02 21:02:45.571 GMT 0008 INFO [orderer.common.server] Main -> Starting with system channel: syschannel, consensus type: solo
2023-01-02 21:02:45.574 GMT 0009 INFO [certmonitor] trackCertExpiration -> The enrollment certificate will expire on 2027-11-10 13:41:11 +0000 UTC
2023-01-02 21:02:45.577 GMT 000a PANI [orderer.commmon.multichannel] initSystemChannel -> Error creating chain support: error retrieving consenter of type: solo
panic: Error creating chain support: error retrieving consenter of type: solo

goroutine 1 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00014d380, {0x0, 0x0, 0x0})
	/home/test/go/src/github.com/hm3736485/fabric/vendor/go.uber.org/zap/zapcore/entry.go:234 +0x49b
go.uber.org/zap.(*SugaredLogger).log(0xc00011c010, 0x4, {0xf2902b?, 0x109fd60?}, {0xc00012c628?, 0x757948?, 0xc000897260?}, {0x0, 0x0, 0x0})
	/home/test/go/src/github.com/hm3736485/fabric/vendor/go.uber.org/zap/sugar.go:227 +0xee
go.uber.org/zap.(*SugaredLogger).Panicf(...)
	/home/test/go/src/github.com/hm3736485/fabric/vendor/go.uber.org/zap/sugar.go:159
github.com/hyperledger/fabric/common/flogging.(*FabricLogger).Panicf(...)
	/home/test/go/src/github.com/hm3736485/fabric/common/flogging/zap.go:74
github.com/hyperledger/fabric/orderer/common/multichannel.(*Registrar).initSystemChannel(0xc0000f4480, {0xc0004838f0?, 0x1, 0xc000158b90?})
	/home/test/go/src/github.com/hm3736485/fabric/orderer/common/multichannel/registrar.go:248 +0x492
github.com/hyperledger/fabric/orderer/common/multichannel.(*Registrar).init(0xc0000f4480, 0xc0003ef5e0?)
	/home/test/go/src/github.com/hm3736485/fabric/orderer/common/multichannel/registrar.go:164 +0x79
github.com/hyperledger/fabric/orderer/common/multichannel.(*Registrar).Initialize(0xc0000f4480, 0xc000154c30?)
	/home/test/go/src/github.com/hm3736485/fabric/orderer/common/multichannel/registrar.go:144 +0x33
github.com/hyperledger/fabric/orderer/common/server.initializeMultichannelRegistrar(_, _, _, {0x0, {0x0, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...}, ...)
	/home/test/go/src/github.com/hm3736485/fabric/orderer/common/server/main.go:817 +0x3c5
github.com/hyperledger/fabric/orderer/common/server.Main()
	/home/test/go/src/github.com/hm3736485/fabric/orderer/common/server/main.go:243 +0x15a7
main.main()
	/home/test/go/src/github.com/hm3736485/fabric/cmd/orderer/main.go:15 +0x17
```

Is there documentation for configuring development mode with a supported Orderer implementation?

Alternatively, are there any changes that can be made to configtx.yaml or other config files to support Raft so development mode can be used?

This is a significant blocker as development of chaincode is much more time consuming without being able to reload chaincode in between edits. 

This is reproducible on multiple systems. The above was generated on Xubuntu 22.04.

Thank you,

**Comment by denyeart** [comment]
@mbwhite For chaincode iterative development, is the plan to phase out DevMode in favor of one of:
-local peer with chaincode-as-a-service
-Microfab container

**Comment by mbwhite** [comment]
Hello - yes that's correct.

**Comment by hm3736485** [comment]
Thank you, is there an alternative for iterative chaincode development at the moment?

**Comment by mbwhite** [comment]
@hm3736485 with MicroFab (and chaincode as a service) you can do that today. 
- Start microfab
- Do a simple chaincode deployment
- Start/stop/rework/restart the chaincode as many times as you wish - without redeployment

The 'full-stack-asset-transfer` example (now in Fabric Samples) walks you through this... 

https://github.com/hyperledger/fabric-samples/blob/main/full-stack-asset-transfer-guide/docs/SmartContractDev/01-Exercise-Getting-Started.md

**Comment by hm3736485** [comment]
I see, thank you.
