### ISSUE TITLE
Failed getting channel mychannel's ledger: error decoding the block number: error decoding varint with proto.Buffer: unexpected EOF

### ISSUE THREAD

**Issue by eshwar-gatram** [hyperledger/fabric#4162]
### Description

**Network configuration**
1. Fabric version: 2.4
2. Consensus: RAFT
3. Single Org setup with 2 peers and 3 orderers

**The above network was deployed using kubernetes 

I was load testing the network with caliper where I created a scenario where disk got filled and for the first few times the orderers and peers where crashing afterwards they were able to restart when space was available but once in a while the orderers go into crash back loop off with the following error 

2023-04-17 05:35:10.193 UTC 0004 INFO [orderer.common.server] initializeServerConfig -> Starting orderer with TLS enabled
2023-04-17 05:35:10.279 UTC 0005 INFO [orderer.common.server] Main -> Not bootstrapping the system channel because of existing channels
2023-04-17 05:35:10.288 UTC 0006 INFO [blkstorage] syncIndex -> Start building index from block [4144] to last block [5237]
2023-04-17 05:35:10.288 UTC 0007 PANI [orderer.common.server] extractSystemChannel -> Failed getting channel mychannel's ledger: error decoding the block number: error decoding varint with proto.Buffer: unexpected EOF
panic: Failed getting channel mychannel's ledger: error decoding the block number: error decoding varint with proto.Buffer: unexpected EOF

goroutine 1 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0000bc000, {0x0, 0x0, 0x0})
	/go/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/zapcore/entry.go:234 +0x49b
go.uber.org/zap.(*SugaredLogger).log(0xc00059c148, 0x4, {0xf70ad2?, 0x0?}, {0xc000511290?, 0xc000511250?, 0x8698db?}, {0x0, 0x0, 0x0})
	/go/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/sugar.go:234 +0x13b
go.uber.org/zap.(*SugaredLogger).Panicf(...)
	/go/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/sugar.go:159
github.com/hyperledger/fabric/common/flogging.(*FabricLogger).Panicf(...)
	/go/src/github.com/hyperledger/fabric/common/flogging/zap.go:74
github.com/hyperledger/fabric/orderer/common/server.extractSystemChannel({0x10cbe20, 0xc0001b2660}, {0x10d0c68, 0xc0005a88c0})
	/go/src/github.com/hyperledger/fabric/orderer/common/server/main.go:406 +0x188
github.com/hyperledger/fabric/orderer/common/server.Main()
	/go/src/github.com/hyperledger/fabric/orderer/common/server/main.go:149 +0x965
main.main()
	/go/src/github.com/hyperledger/fabric/cmd/orderer/main.go:15 +0x17

### Steps to reproduce

1. Bring up HLF network with 1 Org which has 2 peers , 3 orderer with system-channel and application channel (mychannel)
2. Deploy Basic chaincode on the network
3. Create a file dump such that there is only few MB space left on the file system
4. Initiate load test using caliper
[orderer.log](https://github.com/hyperledger/fabric/files/11246617/orderer.log)

**Comment by denyeart** [comment]
Please edit and clarify the reproduction steps. You mentioned once space was added the orderers were able to restart but "once in a while the orderers go into crash back loop." Please clarify "once in a while". It seems the orderers would either be able to restart or they wouldn't. Do you mean some of the orderers hit this issue upon restart? Or orderers that restarted fine hit this issue upon subsequent restarts? Is there a pattern or is it intermittent? Once hit does the orderer fail to restart every subsequent time? Do you really think initiating load using caliper is required to reproduce? Or simply restarting orderer nodes would be sufficient (since it seems like a startup issue rather than a load issue).

**Comment by eshwar-gatram** [comment]
Before adding space to the orderer I am this error:
 
2023-04-21 05:56:34.441 UTC 0004 INFO [orderer.common.server] initializeServerConfig -> Starting orderer with TLS enabled
panic: Error opening leveldb: sync /var/hyperledger/production/orderer/index/000002.ldb: no space left on device

goroutine 1 [running]:
github.com/hyperledger/fabric/common/ledger/util/leveldbhelper.(*DB).Open(0xc0000179f0)
	/go/src/github.com/hyperledger/fabric/common/ledger/util/leveldbhelper/leveldb_helper.go:76 +0x1b9
github.com/hyperledger/fabric/common/ledger/util/leveldbhelper.openDBAndCheckFormat(0xc0000f05e0)
	/go/src/github.com/hyperledger/fabric/common/ledger/util/leveldbhelper/leveldb_provider.go:72 +0x145
github.com/hyperledger/fabric/common/ledger/util/leveldbhelper.NewProvider(0xc0004490c8?)
	/go/src/github.com/hyperledger/fabric/common/ledger/util/leveldbhelper/leveldb_provider.go:60 +0x1d
github.com/hyperledger/fabric/common/ledger/blkstorage.NewProvider(0xc0000af950, 0xc0000af968, {0x10ca4e0, 0x1770240})
	/go/src/github.com/hyperledger/fabric/common/ledger/blkstorage/blockstore_provider.go:70 +0x145
github.com/hyperledger/fabric/common/ledger/blockledger/fileledger.New({0xc00043e1e0, 0x23}, {0x10ca4e0, 0x1770240})
	/go/src/github.com/hyperledger/fabric/common/ledger/blockledger/fileledger/factory.go:103 +0x113
github.com/hyperledger/fabric/orderer/common/server.createLedgerFactory(0x0?, {0x10ca4e0, 0x1770240})
	/go/src/github.com/hyperledger/fabric/orderer/common/server/util.go:24 +0xfb
github.com/hyperledger/fabric/orderer/common/server.Main()
	/go/src/github.com/hyperledger/fabric/orderer/common/server/main.go:115 +0x5b5
main.main()
	/go/src/github.com/hyperledger/fabric/cmd/orderer/main.go:15 +0x17


After this when i add space to orderer then i get the below error and  goes into crashBackLoopOff 

2023-04-21 06:32:58.460 UTC 0004 INFO [orderer.common.server] initializeServerConfig -> Starting orderer with TLS enabled
2023-04-21 06:32:58.513 UTC 0005 INFO [orderer.common.server] Main -> Not bootstrapping the system channel because of existing channels
2023-04-21 06:32:58.520 UTC 0006 INFO [blkstorage] syncIndex -> Start building index from block [10] to last block [3918]
2023-04-21 06:32:58.520 UTC 0007 PANI [orderer.common.server] extractSystemChannel -> Failed getting channel mychannel's ledger: error decoding the block number: error decoding varint with proto.Buffer: unexpected EOF
panic: Failed getting channel mychannel's ledger: error decoding the block number: error decoding varint with proto.Buffer: unexpected EOF

goroutine 1 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000218000, {0x0, 0x0, 0x0})
	/go/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/zapcore/entry.go:234 +0x49b
go.uber.org/zap.(*SugaredLogger).log(0xc00052c150, 0x4, {0xf70ad2?, 0x0?}, {0xc00027b290?, 0xc00027b250?, 0x8698db?}, {0x0, 0x0, 0x0})
	/go/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/sugar.go:234 +0x13b
go.uber.org/zap.(*SugaredLogger).Panicf(...)
	/go/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/sugar.go:159
github.com/hyperledger/fabric/common/flogging.(*FabricLogger).Panicf(...)
	/go/src/github.com/hyperledger/fabric/common/flogging/zap.go:74
github.com/hyperledger/fabric/orderer/common/server.extractSystemChannel({0x10cbe20, 0xc0001772f0}, {0x10d0c68, 0xc00013c910})
	/go/src/github.com/hyperledger/fabric/orderer/common/server/main.go:406 +0x188
github.com/hyperledger/fabric/orderer/common/server.Main()
	/go/src/github.com/hyperledger/fabric/orderer/common/server/main.go:149 +0x965
main.main()
	/go/src/github.com/hyperledger/fabric/cmd/orderer/main.go:15 +0x17


@denyeart  I have observed the above pattern and caliper is just to put load on the network so that the disk filled when there transaction are being committed. I have tried restarting the orderers i am getting the same decoding error so i think this is startup problem

**Comment by denyeart** [comment]
@manish-sethi What do you think? The last block that was written can't be deserialized upon orderer restart. Does this indicate that the last block that was being written prior to running out of disk space got persisted partially or with corruption?

**Comment by manish-sethi** [comment]
@denyeart - This does not seem to be related to partial block written situation. We anyways detect and reverse that situation at start. In any case, what puzzles me is the log entry - `Start building index from block [10] to last block [3918]`. How come index is this much far behind the last committed block? One suspicion goes whether the index and block files are from the same orderer or are they getting mixed up in this environment.

@eshwar-gatram - Can you investigate your environment based on above lines? Otherwise, full logs (with debug mode)  before and after start of the orderer may help detect further.

**Comment by eshwar-gatram** [comment]
@manish-sethi - I have reset the orderer in debug mode and these are the logs. orderer-initial.log logs of orderer at start, orderer-diskFilled-state.log logs of orderer when there is no space left and orderer-crashBackLoopoff.log logs after which the orderer is not starting. 
[orderer-intial.log](https://github.com/hyperledger/fabric/files/11358555/orderer-intial.log)
[orderer-diskFilled-state.log](https://github.com/hyperledger/fabric/files/11358556/orderer-diskFilled-state.log)
[orderer-crashBackloopoff.log](https://github.com/hyperledger/fabric/files/11358557/orderer-crashBackloopoff.log)

**Comment by denyeart** [comment]
@eshwar-gatram I checked the logs... the first ones are at block 0, but the crashBackloopoff log seems to jump ahead to block 1810 whiles indexes are still at 705:

```
[36m2023-04-29 06:44:14.486 UTC 08f0 DEBU[0m [blkstorage] [36;1msyncIndex[0m -> Last block indexed [705], Last block present in block files [1810]
[34m2023-04-29 06:44:14.486 UTC 08f1 INFO[0m [blkstorage] [34;1msyncIndex[0m -> Start building index from block [706] to last block [1810]
```

The question remains, what happened inbetween these logs? Did you process 1810 blocks? Why are the indexes so far behind? Did you hit disk full error while processing a block? Please share the logs between blocks 705 and 1810 so that we can understand how it got into a crash state.
