### ISSUE TITLE
Panic on leveldb

### ISSUE THREAD

**Issue by dviejokfs** [hyperledger/fabric#5001]
### Description

Sometimes, when load is heavy on the peers, the peer crashes with the following error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c pc=0x12df6f8]

goroutine 9216936 [running]:
[github.com/syndtr/goleveldb/leveldb.(*dbIter).Release(0xc00c41dd40)](https://github.com/syndtr/goleveldb/leveldb.(*dbIter).Release(0xc00c41dd40))
 /vendor/[github.com/syndtr/goleveldb/leveldb/db_iter.go:352](https://github.com/syndtr/goleveldb/leveldb/db_iter.go:352) +0x118
[github.com/hyperledger/fabric/core/ledger/kvledger/txmgmt/statedb/stateleveldb.(*kvScanner).Close(0x0?)](https://github.com/hyperledger/fabric/core/ledger/kvledger/txmgmt/statedb/stateleveldb.(*kvScanner).Close(0x0?))
 /core/ledger/kvledger/txmgmt/statedb/stateleveldb/stateleveldb.go:338 +0x1c
[github.com/hyperledger/fabric/core/ledger/kvledger/txmgmt/txmgr.(*resultsItr).Close(...)](https://github.com/hyperledger/fabric/core/ledger/kvledger/txmgmt/txmgr.(*resultsItr).Close(...))
 /core/ledger/kvledger/txmgmt/txmgr/query_executor.go:495
 ```

### Steps to reproduce

It's hard to reproduce it since it happens with a lot of load, 300tps/second with chaincode that has custom logic and most likely needs optimization.

But the conditions are:
- High load on the peers
- State db (leveldb) under stress
- Chaincode as a service in Kubernetes

**Comment by sam-at-luther** [comment]
The conditions and panic look similar to the ones we're seeing here: https://github.com/hyperledger/fabric/issues/5048

**Comment by pfi79** [comment]
@dviejokfs I really want to get to the bottom of the error.
1. in your panic stacktrace I don't see that the code goes through the place you corrected.

2. the error can be either in the goleveldb library or in incorrect parameters passed to the GetStateByRange method (maybe they are overwritten somewhere along the way, then it's an error in the fabric). 
What is the best way to separate one from the other? 
If it is an error in goleveldb, then this is not the only place to insert recover. 

I suggest you to insert logs in the place where you make changes and logs in the call in the chaincode. And check that the input parameters in GetStateByRange are correct and do not change along the whole path.
